# test.type = 'error'
#
# [test.metadata]
# error = 'EvalError::BlameError'
((fun x => x) : Number -> Number) "a"
